version: '3'

services:
  backend1:
    build: .
    container_name: backend1
    volumes:
      - ./backend1/index.html:/usr/share/nginx/html/index.html
    networks:
      backend-net

  backend2:
    build: .
    container_name: backend2
    volumes:
      - ./backend2/index.html:/usr/share/nginx/html/index.html
    networks:
      backend-net
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      backend-net

networks:
  backend-net:
    driver: bridge