version: '3'

services:
  backend1:
    image: nginx:alpine
    container_name: backend1
    volumes:
      - ./backend1/index.html:/usr/share/nginx/html/index.html
    networks:
      - backend-net

  backend2:
    image: nginx:alpine
    container_name: backend2
    volumes:
      - ./backend2/index.html:/usr/share/nginx/html/index.html
    networks:
      - backend-net

  haproxy:
    image: haproxy:alpine
    container_name: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "8080:80"
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
