version: '3.9'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
    ports:
      - "8082:8082"
      - "8081:80"
    networks:
      - backend-net

  backend1:
    image: nginx:alpine
    container_name: backend1
    volumes:
      - ./backend1/index.html:/usr/share/nginx/html/index.html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend1.rule=Host(`backend1.localhost`)"
      - "traefik.http.services.backend1.loadbalancer.server.port=80"
    networks:
      - backend-net

  backend2:
    image: nginx:alpine
    container_name: backend2
    volumes:
      - ./backend2/index.html:/usr/share/nginx/html/index.html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend2.rule=Host(`backend2.localhost`)"
      - "traefik.http.services.backend2.loadbalancer.server.port=80"
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
